import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession } from 'next-auth/react'
import Link from 'next/link'

export default function Home() {
  const { data: session, status } = useSession();
  console.log({ session, status });

  return (
    <div className={styles.container}>
      <Head>
        <title>Divio NextJs App</title>
        <meta name='description' content='Generated by Divio next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {session?.user?.name ? `${session.user.name}, ` : ''}Welcome to{' '}
          <a href='https://ajchipl.com'>Ajna Chakraa India Private Limited!</a>
        </h1>

        <div className={styles.description}>
          <h1></h1>
          <p>
            This is the home page. You can view it without being logged in.
          </p>
          <Image
            src='https://avatars.githubusercontent.com/u/15612818?v=4'
            alt='Welcome to GitHub'
            width={200}
            height={200}
          />
          <p>
          Go to the <Link href="/protected">protected page</Link>
          </p>
          <p>Login with your credentials</p>
        </div>

        <div className={styles.grid}>
          <a href='https://ajchipl.com/career' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>
              Find in-depth information about AJCHIPL features and API.
            </p>
          </a>

          <a href='https://ajchipl.com/contact' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about AJCHIPL in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/host2india'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example AJCHIPL projects.</p>
          </a>

          <a
            href='https://vercel.com/host2india/minting-divio'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your AJCHIPL site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://divioimdb.netlify.app/'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
